#!/usr/bin/env python3
"""
Seed the knowledge_documents table from the NRG Playbook Trello export.
Generates SQL INSERT statements to run in Supabase SQL Editor.

Usage:
  python3 scripts/seed-knowledge-base.py > /tmp/seed-knowledge.sql
  # Then paste the output into the Supabase SQL Editor and run it.
"""

import json
import re
import sys
import uuid

PLAYBOOK_PATH = "/Users/laura-brynnneuhoff/Downloads/GWKhL160 - nrg-playbook.json"

# Cards to skip (decorative / navigation cards with no real content)
SKIP_NAMES = {
    "🏅",
    "The Playbook is an electronic library of Resources to support you in executing all the important duties of of managing an NRG restaurant. Here you will find a wealth of information including forms, SOPs, guides, how-tos, and best practices. We will continue improving and expanding this resource over time. If something is missing that would be helpful to you, please let us know!",
    "Below you will find resources you will access most frequently. This collection includes materials and tools that are relevant on a daily basis.",
}

# State scoping rules based on card name keywords
def get_applicable_states(name: str, desc: str) -> list[str]:
    name_lower = name.lower()
    desc_lower = desc.lower()

    if "dc manuals" in name_lower or "dc hourly" in desc_lower or "dc salary" in desc_lower:
        return ["dc"]
    if "md/va/nola" in name_lower or "md/va/nola" in desc_lower:
        return ["va", "md", "la"]
    if "nola" in name_lower and ("insurance" in name_lower or "health" in name_lower):
        return ["la"]
    if "dmv" in name_lower and ("insurance" in name_lower or "health" in name_lower):
        return ["dc", "va", "md"]
    if "nola" in name_lower:
        return ["la"]
    # Default: universal (all states)
    return ["dc", "va", "md", "la"]

# Category slug mapping
CATEGORY_SLUGS = {
    "👋 START HERE!": "start-here",
    "Who's Who & What's What": "whos-who",
    "Manager Responsibilities + Procedures": "manager-responsibilities",
    "Repairs & Maintenance (R&M)": "repairs-maintenance",
    "Accounting Manual": "accounting",
    "Marketing + Communications (MarComm)": "marketing",
    "HR: Benefits, Manuals, Forms & Procedures": "hr",
    "Hiring and Staffing (incl. Discipline)": "hiring-staffing",
    "Staff Training": "staff-training",
}

def escape_sql_string(s: str) -> str:
    """Escape a string for use in a SQL literal."""
    return s.replace("'", "''")

def main():
    with open(PLAYBOOK_PATH) as f:
        data = json.load(f)

    lists = {l["id"]: l["name"] for l in data.get("lists", [])}
    cards = [c for c in data.get("cards", []) if not c.get("closed")]
    checklists_by_id = {cl["id"]: cl for cl in data.get("checklists", [])}

    print("-- NRG Playbook Knowledge Base Seed")
    print("-- Generated by scripts/seed-knowledge-base.py")
    print("-- Run this in the Supabase SQL Editor after creating the knowledge_documents table.")
    print()
    print("DELETE FROM knowledge_documents WHERE source = 'nrg-playbook';")
    print()

    inserted = 0
    skipped = 0

    for card in cards:
        name = card.get("name", "").strip()
        desc = card.get("desc", "").strip()

        # Skip decorative cards
        if name in SKIP_NAMES or not name:
            skipped += 1
            continue

        # Skip cards with no meaningful content (just a link and nothing else)
        content = desc
        if not content:
            content = ""

        # Append checklist content
        for cl_id in card.get("idChecklists", []):
            cl = checklists_by_id.get(cl_id)
            if cl:
                content += f"\n\n**{cl['name']}**\n"
                for item in cl.get("checkItems", []):
                    content += f"- {item['name']}\n"

        list_name = lists.get(card["idList"], "")
        category = CATEGORY_SLUGS.get(list_name, "general")
        applicable_states = get_applicable_states(name, content)
        states_array = "{" + ",".join(applicable_states) + "}"
        doc_id = str(uuid.uuid4())

        name_escaped = escape_sql_string(name)
        content_escaped = escape_sql_string(content)
        category_escaped = escape_sql_string(category)
        list_name_escaped = escape_sql_string(list_name)

        print(f"INSERT INTO knowledge_documents (id, title, content, category, category_label, applicable_states, source) VALUES (")
        print(f"  '{doc_id}',")
        print(f"  '{name_escaped}',")
        print(f"  '{content_escaped}',")
        print(f"  '{category_escaped}',")
        print(f"  '{list_name_escaped}',")
        print(f"  '{states_array}',")
        print(f"  'nrg-playbook'")
        print(f");")
        print()
        inserted += 1

    print(f"-- Done: {inserted} documents inserted, {skipped} skipped", file=sys.stderr)

if __name__ == "__main__":
    main()
